export { default as angryRating } from './feedback/rating-angry.png'
export { default as blushRating } from './feedback/rating-blush.png'
export { default as heartEyesRating } from './feedback/rating-heart-eyes.png'
export { default as neutralRating } from './feedback/rating-neutral.png'
export { default as smirkRating } from './feedback/rating-smirk.png'

export { default as docsArtwork } from './home/docs-art.png'
export { default as imageArtwork } from './home/image-art.png'
export { default as innovationArtwork } from './home/innovation-art.png'
export { default as moreToolsLeftArtwork } from './home/more-tools-left.png'
export { default as moreToolsMiddleArtwork } from './home/more-tools-middle.png'
export { default as moreToolsRightArtwork } from './home/more-tools-right.png'
export { default as slidesArtwork } from './home/slides-art.png'
export { default as threeDArtwork } from './home/threed-art.png'
export { default as videoArtwork } from './home/video-art.png'

export { default as exploreMediaOne } from './generations/explore-01.png'
export { default as exploreMediaTwo } from './generations/explore-02.png'
export { default as exploreMediaThree } from './generations/explore-03.png'
export { default as exploreMediaFour } from './generations/explore-04.png'
export { default as exploreMediaFive } from './generations/explore-05.png'

export { default as addImageIcon } from './icons/add-image.svg'
export { default as aspectRatioIcon } from './icons/aspect-ratio.svg'
export { default as durationIcon } from './icons/duration.svg'
export { default as filterIcon } from './icons/filter.svg'
export { default as logomark } from './icons/logomark.svg'
export { default as resolutionIcon } from './icons/resolution.svg'
export { default as sidebarThreeDIcon } from './icons/sidebar-3d.svg'
export { default as sidebarDocsIcon } from './icons/sidebar-docs.svg'
export { default as sidebarHomeIcon } from './icons/sidebar-home.svg'
export { default as sidebarImagesIcon } from './icons/sidebar-images.svg'
export { default as sidebarProjectsIcon } from './icons/sidebar-projects.svg'
export { default as sidebarVideoIcon } from './icons/sidebar-video.svg'
export { default as sidebarWorkspaceIcon } from './icons/sidebar-workspace.svg'
